import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import ProductProvider from "@/components/Context";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cash desk ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProductProvider>
        <body className={inter.className}>
          <ToastContainer position="bottom-right" autoClose={5000} />
          <Navigation />
          <main className={"main"}>{children}</main>
        </body>
      </ProductProvider>
    </html>
  );
}
